apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: conference
  name: conference
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: conference
    spec:
      containers:
      - env:
        - name: EUREKA
          value: eureka-server
        - name: MYSQL_HOST
          value: conference-db
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_PWD
          value: "123123"
        - name: MYSQL_USER
          value: root
        image: conference
        name: conference
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
