apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: kafka0
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: LISTENER_ALICE://localhost:9092,LISTENER_BOB://kafka0:29092
        - name: KAFKA_CREATE_TOPICS
          value: NotificationTopic:1:1
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: LISTENER_BOB
        - name: KAFKA_LISTENERS
          value: LISTENER_ALICE://kafka0:9092,LISTENER_BOB://kafka0:29092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: LISTENER_BOB:PLAINTEXT, LISTENER_ALICE:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: wurstmeister/kafka
        name: kafka
        ports:
        - containerPort: 9092
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: kafka0-claim0
      restartPolicy: Always
      volumes:
      - name: kafka0-claim0
        persistentVolumeClaim:
          claimName: kafka0-claim0
status: {}
