version: '3'
services:
  conference:
    build: .
    restart: always
    environment:
      MYSQL_HOST: conference-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PWD: 123123
    ports:
      - "8080:8080"
    depends_on:
      - conference-db
  conference-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: conference
    ports:
      - "3306:3306"
