apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  type: NodePort
  ports:
  - name: "8082"
    nodePort: 31001
    port: 8082
    targetPort: 8082
  selector:
    io.kompose.service: api-gateway
