apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
      - image: kyriconf/api-gateway:latest
        name: api-gateway
        ports:
        - containerPort: 8082
      restartPolicy: Always
  selector:
    matchLabels:
      io.kompose.service: api-gateway