apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
      - image: taskbeez/eureka-server:master
        name: eureka-server
        ports:
        - containerPort: 8761
      hostname: eureka-server
      restartPolicy: Always
  selector:
    matchLabels:
      io.kompose.service: eureka-server