apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  type: NodePort
  ports:
  - name: "8761"
    nodePort: 31000
    port: 8761
    targetPort: 8761
  selector:
    io.kompose.service: eureka-server