apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka0