apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sponsorship-db
  name: sponsorship-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: sponsorship-db
    spec:
      containers:
      - image: postgres
        name: sponsorship-db
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
  selector:
    matchLabels:
      io.kompose.service: sponsorship-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-data
  name: db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi