apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sponsorship-service
  name: sponsorship-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: sponsorship-service
    spec:
      containers:
      - env:
        - name: SPONSORSHIP_DB_HOST
          value: sponsorship-db
        - name: SPONSORSHIP_DB_NAME
          value: postgres
        - name: SPONSORSHIP_DB_PASSWORD
          value: postgres
        - name: SPONSORSHIP_DB_PORT
          value: "5432"
        - name: SPONSORSHIP_DB_USERNAME
          value: postgres
        - name: SPONSORSHIP_SERVICE_PORT
          value: "8080"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: localhost:9092,kafka0:31005
        image: kyriconf/sponsorship:latest
        name: sponsorship-service
        ports:
        - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      io.kompose.service: sponsorship-service