version: "3.1"
services:
  db:
    image: postgres
    container_name: "sponsorship_postgres"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: