version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: "discount_postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./build/db:/var/lib/postgresql/data
  discount:
    environment:
      - PGHOST=db
      - PORT=5432
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - db