version: "3.7"
services:
  eureka-server:
    image:  springcloud/eureka
    hostname: eureka-server
    ports:
      - "8761:8761"
  db:
    image: postgres:latest
    container_name: "discount_postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./build/db:/var/lib/postgresql/data
  discount:
    environment:
      - PGHOST=db
      - PORT=5432
      - APP_PORT=8082
      - EUREKA=eureka-server
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - db