spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PORT:5433}/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
server:
  port: ${APP_PORT:8083}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA:localhost}:8761/eureka/
