spring:
  application:
    name: sponsorship
  datasource:
    url: jdbc:postgresql://postgres_db:5432/postgres
    username: postgres
    password: postgres
  liquibase.change-log: classpath:db/changelog/changelog-master.xml
logging:
  level:
    root: warn
    org.springframework.web: warn
    org.hibernate: warn
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka