api.version.path: /api/v1
spring:
  application:
    name: sponsorship
  datasource:
    url: jdbc:postgresql://${SPONSORSHIP_DB_HOST:sponsorship_db}:${SPONSORSHIP_DB_PORT:5432}/postgres
    username: ${SPONSORSHIP_DB_USERNAME}
    password: ${SPONSORSHIP_DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    # Added to suppress redundant rubbish exception in the log
    open-in-view: false
    # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
logging:
  level:
    root: warn
    org.springframework.web: warn
    org.hibernate: warn
server:
  port: ${SPONSORSHIP_SERVICE_PORT:8080}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url.defaultZone: http://localhost:${EUREKA_PORT:9090}/eureka